wandb_version: 1

ANCHOR:
  desc: null
  value:
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
BACKBONE:
  desc: null
  value: mobilenet_v2
BATCH:
  desc: null
  value: 10
BIAS:
  desc: null
  value: true
BUFFER_SIZE:
  desc: null
  value: 2
CATEGORY:
  desc: null
  value:
  - COCO
CLASS:
  desc: null
  value:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush
DATASET:
  desc: null
  value: coco
DATASET_PATH:
  desc: null
  value: /home/harsper/dataset
FREEZE_BACKBONE:
  desc: null
  value: false
INPUT_SIZE:
  desc: null
  value:
  - 300
  - 300
LR:
  desc: null
  value: 0.0001
MASTER_ADDR:
  desc: null
  value: localhost
MASTER_PORT:
  desc: null
  value: '12355'
MEAN:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
PRETRAINED:
  desc: null
  value: torchvision
PROJECT:
  desc: null
  value: ssd_coco_80
REPORT_EVAL:
  desc: null
  value: false
REPORT_STEP_TRAIN:
  desc: null
  value: 1000
REPORT_STEP_VALID:
  desc: null
  value: 50
REPORT_WANDB:
  desc: null
  value: true
SCALE:
  desc: null
  value:
  - 0.1
  - 0.35
  - 0.5
  - 0.65
  - 0.8
  - 0.95
STD:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
STEPS:
  desc: null
  value:
  - 300000
  - 350000
  - 400000
WEIGHT:
  desc: null
  value: None
WEIGHT_DECAY:
  desc: null
  value: 0
WORKERS:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1678079853.917952
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
      - 9
method:
  desc: null
  value: ssd
