# Project
PROJECT: 'ssd_argoseye'
DATASET_PATH: '/home/harsper/dataset'
DATASET: 'argoseye'
CATEGORY: ['AE1', 'AE2', 'AE3', 'AE4', 'AE5', 'AE6', 'AE7', 'AE8', 'NE5']

# DDP Setting
MASTER_ADDR: 'localhost'
MASTER_PORT: '12355'

# Network
method: 'ssd'
BACKBONE: 'mobilenet_v2' # {'mobilenet_v2'}
PRETRAINED: 'torchvision' # {None, 'torchvision'}
WEIGHT: None # {weight_path}
FREEZE_BACKBONE: False
BIAS: True
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
INPUT_SIZE: [300, 300] # (height, width), min size 224 x 224
CLASS: ['person']
ANCHOR: [6, 6, 6, 6, 6, 6]
# SCALE: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9]
SCALE: [0.1, 0.35, 0.5, 0.65, 0.8, 0.95]

# Training
STEPS: [300000, 350000, 400000]
LR: 0.001
WEIGHT_DECAY: 0.005
BATCH: 10
BUFFER_SIZE: 2
WORKERS: 2


# report
REPORT_WANDB: False
REPORT_STEP_TRAIN: 1000
REPORT_STEP_VALID: 50
REPORT_EVAL: False
