# Project
PROJECT: 'ssd_crowdhuman_2'
DATASET_PATH: '/home/harsper/oddata'
DATASET: 'crowdhuman'
CATEGORY: ['CrowdHuman']

# DDP Setting
MASTER_ADDR: 'localhost'
MASTER_PORT: '12357'

# Network
method: 'ssd'
BACKBONE: 'mobilenet_v2' # {'mobilenet_v2'}
PRETRAINED: None # {None, 'torchvision'}
WEIGHT: None # {weight_path}
FREEZE_BACKBONE: False
BIAS: True
MEAN: [0, 0, 0]
STD: [1, 1, 1]
INPUT_SIZE: [300, 300] # (height, width), min size 224 x 224
CLASS: ['person', 'head']
ANCHOR: [6, 6, 6, 6, 6, 6]
# SCALE: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9]
SCALE: [0.1, 0.35, 0.5, 0.65, 0.8, 0.95]

# Training
STEPS: [300000, 350000, 400000]
LR: 0.0001
BATCH: 10
BUFFER_SIZE: 2
WORKERS: 2

# report
REPORT_WANDB: True
REPORT_STEP_TRAIN: 5000
REPORT_STEP_VALID: 500
REPORT_EVAL: False
