# Network
TASK: ['Object Detection']
METHOD: 'ssd'
TYPE: 'mobilenet_v2' # {'mobilenetv2'}
METRIC: ['mAP']
LOSS: ['Total', 'Class', 'Regression']
BACKBONE_WEIGHT: 'torchvision' # {None, 'torchvision'}
PRETRAINED_WEIGHT: None # weight_path
INPUT_SIZE: [300, 300] # (height, width)


# System
WORKERS: 2 # workers per gpu

#HyperParameter
### Network
BIAS: True
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]

### NMS
TOPK: 200
NMS_IOU_THRESHOLD: 0.5

### Training
STEPLR: [50, 60, 70]
LR: 0.01
BATCH_SIZE_MULTI_GPU: 128 # BATCH_SIZE_MULTI_GPU will divide by GPU_NUM e.g. 256/8=32
WEIGHT_DECAY: 0.0005
MOMENTUM: 0.9

### loss
LOSS_ALPHA: 1.0

### Anchor
ANCHOR_N: [6, 6, 6, 6, 6, 6]
# ANCHOR_SCALE: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9]
ANCHOR_SCALE: [0.1, 0.35, 0.5, 0.65, 0.8, 0.95]
ANCHOR_SIZE: [16, 32, 64, 128, 256, 512] # 1/n, anchor grid

