# Network
TASK: ['Object Detection']
METHOD: 'ssd'
TYPE: 'mobilenet_v2' # {'mobilenetv2'}
METRIC: ['mAP']
LOSS: ['Total', 'Class', 'Regression']
BACKBONE_WEIGHT: 'torchvision' # {None, 'torchvision'}
PRETRAINED_WEIGHT: None # weight_path
INPUT_SIZE: [300, 300] # (height, width)


# System
WORKERS: 2 # workers per gpu

#HyperParameter
### Network
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]

### NMS
TOPK: 200
NMS_IOU_THRESHOLD: 0.5

### Training
STEPLR: [500000, 600000, 700000]
LR: 0.004
BATCH_SIZE_MULTI_GPU: 8 # BATCH_SIZE_MULTI_GPU will divide by GPU_NUM e.g. 256/8=32, Batch size must be greater than 8
WEIGHT_DECAY: 0.0005
MOMENTUM: 0.9

### loss
LOSS_ALPHA: 1.0

### Anchor
ANCHOR_N: [6, 6, 6, 6, 6, 6]
# ANCHOR_SCALE: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9]
ANCHOR_SCALE: [0.1, 0.35, 0.5, 0.65, 0.8, 0.95]
ANCHOR_GRID_W: [19, 10, 5, 3, 2, 1]
ANCHOR_GRID_H: [19, 10, 5, 3, 2, 1]

# Augmentation
HSV_PROB: 1.0
HSV_HGAIN: 0.015
HSV_SGAIN: 0.7
HSV-VGAIN: 0.4

MOSAIC_PROB: 1.0
MOSAIC_CANVAS_RANGE: 1.0

PERSPECTIVE_PROB: 1.0
PERSPECTIVE_DEGREE: 10.0
PERSPECTIVE_TRANSLATE: 0.1
PERSPECTIVE_SCALE: 0.1
PERSPECTIVE_SHEAR: 5.0
PERSPECTIVE_PERSPECTIVE: 0.0