# Network
METHOD: 'ssd'
TYPE: 'mobilenet_v2' # {'mobilenetv2'}
BACKBONE_WEIGHT: 'torchvision' # {None, 'torchvision'}
PRETRAINED_WEIGHT: None # weight_path
INPUT_SIZE: [300, 300] # (height, width), min size 224 x 224

# System
BUFFER_SIZE: 2
WORKERS: 2 # workers per gpu

#HyperParameter
### Network
BIAS: True
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]

### Training
STEPS: [300000, 350000, 400000]
LR: 0.0001
BATCH: 16
WEIGHT_DECAY: 0.00005

### loss
LOSS_ALPHA: 1.0

### Anchor
ANCHOR_N: [6, 6, 6, 6, 6, 6]
# ANCHOR_SCALE: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9]
ANCHOR_SCALE: [0.1, 0.35, 0.5, 0.65, 0.8, 0.95]
ANCHOR_SIZE: [16, 32, 64, 128, 256, 512] # 1/n

# report
REPORT_WANDB: False
REPORT_METRIC: ['mAP']

STEPS_PER_EPOCH: [10000, 500] # Trainig, Valid